config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/help'
  get 'help' => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  
  get 'users/new'
  get 'signup'  => 'users#new'
  resources :users
  
  get 'sessions/new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :patients
  
  post 'receiver' => 'http#create'
  post 'data' => 'http#show'
  post 'data/update' => 'http#click_update'
  post 'data/brush' => 'http#brush_update'
  
  get 'graph/index'
  get 'graph/data', :defaults => { :format => 'json' }
  

end

app/models/patient.rb
class Patient < ActiveRecord::Base
    validates :name, presence: true, length: {maximum: 50}
    validates :description, length: {maximum: 250}
    validates :doctor, presence: true
    validates :status, length: {maximum: 250}
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
    include SessionsHelper
    
    def index
        user = authenticate_user
        
        @patients = Patient.where("doctor = ?", user.id).order('updated_at DESC')
    end
    
    def show
        user = authenticate_user
        
        @patient = Patient.find_by(["id = :i AND doctor = :d", { i: params[:id], d: user.id }])
        
        if @patient.nil?
            flash[:danger] = "Patient does not exist"
            redirect_to :action => "index"
        end
        
        records = Record.select("start_at", "end_at").where("patient = ?", params[:id]).order("start_at ASC").to_a
        @enabled_dates = []
        records.each do |record|
            date_str = Time.at(record.start_at).to_date.to_s
            if (!@enabled_dates.include?(date_str))
               @enabled_dates.push(date_str)
            end
            date_str = Time.at(record.end_at).to_date.to_s
            if (!@enabled_dates.include?(date_str))
                @enabled_dates.push(date_str)
            end
        end
        
        # added types
        @types = Type.select("id","name").to_a
    end
    
    def new
        @patient = Patient.new
    end
    
    def create
        user = authenticate_user
        
        @patient = Patient.new(patient_params)
        @patient.doctor = user.id
        if @patient.save
            flash[:success] = "You added a patient"
            redirect_to :action => "index"
        else
            flash[:danger] = "Failed to add patient"
            render 'new'
        end
    end
    
    def destroy
        user = authenticate_user
        
        patient = Patient.find_by(["id = :i AND doctor = :d", { i: params[:id], d: user.id }])
        patient.destroy if !patient.nil?
        redirect_to :back
    end
    
    private
    
        def patient_params
            params.require(:patient).permit(:name, :description)
        end

end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_button.html.erb
<div style="text-align: center">
  <%= link_to "Add a patient", new_patient_path, :class => 'btn', :style => 'width:30%' %>
</div>

app/views/patients/_datetimepicker.html.erb
<div class='container'>
<div class='col-md-5'>
<p><b>Start time</b></p>
  <div class="form-group">
      <div class='input-group date' id='datetimepicker6'>
          <input type='text' class="form-control" />
          <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
          </span>
      </div>
  </div>
</div>
<div class='col-md-5'>
<p><b>End time</b></p>
  <div class="form-group">
      <div class='input-group date' id='datetimepicker7'>
          <input type='text' class="form-control" />
          <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
          </span>
      </div>
  </div>
</div>
</div>

<%= javascript_tag do %>
      $(function () {
        // if the browser keeps the last user input dates
        var datestr1 = $('#datetimepicker6 :input').val();
        var datestr2 = $('#datetimepicker7 :input').val();

        if (datestr1 !== undefined && datestr1 !== "" && datestr2 !== undefined && datestr2 !== "") {
          selection_range[0] = moment(datestr1, "MM/DD/YYYY h:mm A").toDate();
          console.log(moment(datestr1, "MM/DD/YYYY h:mm A"));
          selection_range[1] = moment(datestr2, "MM/DD/YYYY h:mm A").toDate();
          console.log(moment(datestr2, "MM/DD/YYYY h:mm A"));
          console.log(selection_range);
        }

        console.log(<%= raw(@enabled_dates) %>);
        $('#datetimepicker6').datetimepicker({
          enabledDates: <%= raw(@enabled_dates) %>
        });
        $('#datetimepicker7').datetimepicker({
          enabledDates: <%= raw(@enabled_dates) %>
        });
        $("#datetimepicker6").on("dp.change", function (e) {
            $('#datetimepicker7').data("DateTimePicker").minDate(e.date);
            selection_range[0] = $('#datetimepicker6').data("DateTimePicker").date().toDate();
            console.log(selection_range);
            if (selection_range.length === 2 && selection_range[0] !== undefined && selection_range[1] !== undefined && signals.length > 0) {
              getData();
            }
        });
        $("#datetimepicker7").on("dp.change", function (e) {
            $('#datetimepicker6').data("DateTimePicker").maxDate(e.date);
            selection_range[1] = $('#datetimepicker7').data("DateTimePicker").date().toDate();
            console.log(selection_range);
            if (selection_range.length === 2 && selection_range[0] !== undefined && selection_range[1] !== undefined && signals.length > 0) {
              getData();
            }
        });
    });
<% end %>

app/views/patients/_empty.html.erb
<h2><%= "You don't have any patients at this point :\\" %></h2>

app/views/patients/_icheck.html.erb
<span id="signals">
  <% @types.each do |type| -%>
  <label class="signal-selection"><input type="checkbox" class='icheck-me' data-skin="square" data-color="blue" type_id=<%= type.id %>> <%= type.name %></label>
  <% end -%>
</span>

<%= javascript_tag do %>

function icheck(){
  if($(".icheck-me").length > 0){
    $(".icheck-me").each(function(){
      var $el = $(this);
      var skin = ($el.attr('data-skin') !== undefined) ? "_" + $el.attr('data-skin') : "",
      color = ($el.attr('data-color') !== undefined) ? "-" + $el.attr('data-color') : "";
      var opt = {
        checkboxClass: 'icheckbox' + skin + color,
        radioClass: 'iradio' + skin + color,
      }
      $el.iCheck(opt);
    });
  }
}

$(function(){
  icheck();
  $(".icheckbox_square-blue").css("margin", "5px");
  //$('input').iCheck('uncheck');
  $(function() {
    $('.icheck-me').each(function() {
      if ($(this).parent().hasClass("checked")) {
        signals.push(+($(this).attr("type_id")));
      }
    });
    console.log(signals);
    if (selection_range.length === 2 && selection_range[0] !== undefined && selection_range[1] !== undefined && signals.length > 0) {
      getData();
    }
  });

  $('.icheck-me').on('ifChecked', function(event) {
    signals.push(+(event.currentTarget.attributes.type_id.nodeValue));
    console.log(signals);
    clearChart();
    getData();
  });

  $('.icheck-me').on('ifUnchecked', function(event) {
    var type_id = +(event.currentTarget.attributes.type_id.nodeValue);
    var index = signals.indexOf(type_id);
    if (index >= 0) {
      signals.splice( index, 1 );
    }
    console.log(signals);
    clearChart();
    if (selection_range.length === 2 && selection_range[0] !== undefined && selection_range[1] !== undefined && signals.length !== 0) { 
      getData();
    }
  });

})
<% end %>

app/views/patients/_list.html.erb
<ul>
  <% @patients.each do |patient| %>
    <li>
      <img src="http://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50.jpg">
      <h3><%= patient.name %></h3>
      <nav class="patients_list_nav">
	      <ul>
	        <li><%= link_to "Show", patient_path(:id=>patient.id) %></li>
    	    <li><a href="#">Edit</a></li>
		      <li><%= link_to "Delete", patient_path(:id=>patient.id), method: :delete, data: { confirm: "Are you sure?" } %></li>
		      <li><a href="#">Contact</a></li>
		    </ul>
	    </nav>
    </li>
  <% end %>
</ul>

app/views/patients/index.html.erb
<% provide(:title, "My Patients") %>
<div class="row">
  <div class="list_long">
    <section class="patients_list">
    	<% if !@patients.empty? %>
          <%= render 'patients/list' %>
        <% else %>
          <%= render 'patients/empty' %>
        <% end %>
        <%= render 'patients/button' %>
    </section>
  </div>
</div>

app/views/patients/new.html.erb
<% provide(:title, 'New Patient') %>
<h1>Add a Patient</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@patient) do |f| %>
      <%= render 'shared/error_messages_patient' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :status %>
      <%= f.text_field :status, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>

      <%= f.submit "Add patient", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/patients/show.html.erb
<% provide(:title, @patient.name) %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <img class="gravatar" src="https://secure.gravatar.com/avatar/c05b751d68fb8995cc3c7e4fbc1580dc">
        <%= @patient.name %>
      </h1>
    </section>
  </aside>
</div>

<div class="timepicker">
  <%= render 'patients/datetimepicker' %>
</div>

<span id="nav_btns">
  <button type="button" onclick="shiftChart('backward')">&lt;&lt; Back</button>
  <button type="button" onclick="shiftChart('forward')">Advance &gt;&gt;</button>
  <!-- <button type="button" onclick="getData()">Get Chart!</button> -->
  <!-- <button type="button" onclick="clearChart()">Clear!</button> -->
</span>

<%= render 'patients/icheck' %>

<div class="monitor">
  <div class="d3_chart" id="ekg"></div>
</div>

<%= javascript_tag do %>
  var selection_range = [];
  var signals = [];
  var patient_id = <%= @patient.id %>;

  function getData() {
    if (selection_range.length < 2) {
      alert("Please select a proper range");
      return;
    }
    if (signals.length == 0) {
      alert("Please select at least one signal");
      return;
    }

    $.ajax({
      type: "POST",
      url: '/data',
      data: {
        patient: <%= @patient.id %>,
        range: selection_range,
        types: signals
      },
      success: function(data) {
        if ($("#ekg").html() == "") {
          chart1 = sliderChart().setData(data, true).render();
        } else {
          //console.log(data);
          chart1.setData(data, true).update();
        }
      }
    });
  }

  function clearChart() {
    $("#ekg").html("");
  }

  function shiftChart(option) {
    if ($("#ekg").html() === "") {
      return;
    }
    var diff = 10;
    if (option === "forward") {
      $('#datetimepicker6').data("DateTimePicker").date(new Date(selection_range[0].getTime() + diff*60000));
      $('#datetimepicker7').data("DateTimePicker").date(new Date(selection_range[1].getTime() + diff*60000));
    } else if (option === "backward") {
      $('#datetimepicker6').data("DateTimePicker").date(new Date(selection_range[0].getTime() - diff*60000));
      $('#datetimepicker7').data("DateTimePicker").date(new Date(selection_range[1].getTime() - diff*60000));
    }
    getData();
  }

  $(document).ready(function() {
    var dispatcher = new WebSocketRails('localhost:3000/websocket');
    var update_channel = dispatcher.subscribe('update12');
    update_channel.bind('new', function(data) {
      //$("#ekg").text("");
      console.log(data);
      data = JSON.parse(data);
      chart1.setData(data, true).update();
    });
  });

<% end %>